apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-ui
spec:
  host: argo.streakcard.com
  prefix: /
  service: argocd-server:443
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server-cli
  namespace: argocd
spec:
  host: argo.streakcard.com:443
  prefix: /
  service: argocd-server:443
